import mutual1 from "../assets/mock-image/2mutual.jpg";
import mutual2 from "../assets/mock-image/1mutual.jpg";
import mutual3 from "../assets/mock-image/3mutual.jpg";
import mutual4 from "../assets/mock-image/5mutual.jpg";
import snappImage from "../assets/mock-image/2mutual.jpg";

export const mockMutual = [
  { id: 1, name: "Jack", profile_img: mutual1, snappy_username: "jack111" },
  {
    id: 2,
    name: "Aaron",
    profile_img: mutual2,
    snappy_username: "aaron63211",
  },
  {
    id: 3,
    name: "Antony",
    profile_img: mutual3,
    snappy_username: "antony76677",
  },
  {
    id: 4,
    name: "Jenifer",
    profile_img: mutual4,
    snappy_username: "jenefier1213",
  },
];

export const mockDiscoverJokes = [
  {
    id: 1,
    question: "Why did the tomato turn red?",
    answer: "Because it saw the salad dressing!",
  },
  {
    id: 2,
    question: "What do you call a bear with no teeth?",
    answer: "A gummy bear!",
  },
  {
    id: 3,
    question: "Why don't scientists trust atoms?",
    answer: "Because they make up everything!",
  },
  {
    id: 4,
    question: "What do you call a fake noodle?",
    answer: "An impasta!",
  },
  {
    id: 5,
    question: "Why did the cookie go to the doctor?",
    answer: "Because it was feeling crumbly!",
  },
  {
    id: 6,
    question: "What do you call a lazy kangaroo?",
    answer: "A pouch potato!",
  },
  {
    id: 7,
    question: "Why did the chicken cross the playground?",
    answer: "To get to the other slide!",
  },
  {
    id: 8,
    question: "What do you call a snowman with a six-pack?",
    answer: "An abdominal snowman!",
  },
  {
    id: 9,
    question: "Why did the math book look so sad?",
    answer: "Because it had too many problems!",
  },
  {
    id: 10,
    question: "Why did the grape stop in the middle of the road?",
    answer: "Because it ran out of juice!",
  },
  {
    id: 11,
    question: "What do you call a sleeping bull?",
    answer: "A bulldozer!",
  },
  {
    id: 12,
    question: "Why did the bicycle fall over?",
    answer: "Because it was two-tired!",
  },
  {
    id: 13,
    question: "What do you call a belt made out of watches?",
    answer: "A waist of time!",
  },
  {
    id: 14,
    question: "Why don't scientists trust atoms?",
    answer: "Because they make up everything!",
  },
  {
    id: 15,
    question: "What do you call a belt made out of watches?",
    answer: "A waist of time!",
  },
  {
    id: 16,
    question: "Why did the banana go to the doctor?",
    answer: "Because it wasn't peeling well!",
  },
  {
    id: 17,
    question: "What do you get when you cross a snowman and a shark?",
    answer: "Frostbite!",
  },
  {
    id: 18,
    question: "Why don't oysters share their pearls?",
    answer: "Because they're shellfish!",
  },
  {
    id: 19,
    question: "What do you call a fake noodle?",
    answer: "An impasta!",
  },
  {
    id: 20,
    question: "Why did the chicken go to the seance?",
    answer: "To talk to the other side!",
  },
];

export const mockDiscoverfacts = [
  {
    id: 1,
    question: "What is the tallest mountain in the world?",
    answer: "Mount Everest.",
  },
  {
    id: 2,
    question: "What is the capital city of Australia?",
    answer: "Canberra.",
  },
  {
    id: 3,
    question: "How many planets are there in our solar system?",
    answer: "There are eight planets in our solar system.",
  },
  {
    id: 4,
    question: "Which animal is known as the 'king of the jungle'?",
    answer: "Lions.",
  },
  {
    id: 5,
    question: "What is the largest organ in the human body?",
    answer: "The skin.",
  },
  {
    id: 6,
    question: "What is the currency of Japan?",
    answer: "Japanese Yen.",
  },
  {
    id: 7,
    question: "What is the chemical symbol for gold?",
    answer: "Au.",
  },
  {
    id: 8,
    question: "Which is the largest ocean on Earth?",
    answer: "The Pacific Ocean.",
  },
  {
    id: 9,
    question: "What is the national animal of Canada?",
    answer: "The beaver.",
  },
  {
    id: 10,
    question: "What is the fastest land animal?",
    answer: "The cheetah.",
  },
  {
    id: 11,
    question: "What year did the first manned moon landing occur?",
    answer: "1969.",
  },
  {
    id: 12,
    question: "How many bones are in the human body?",
    answer: "There are 206 bones in the human body.",
  },
  {
    id: 13,
    question: "What is the largest continent?",
    answer: "Asia.",
  },
  {
    id: 14,
    question: "Who painted the Mona Lisa?",
    answer: "Leonardo da Vinci.",
  },
  {
    id: 15,
    question: "Which planet is known as the 'Red Planet'?",
    answer: "Mars.",
  },
  {
    id: 16,
    question: "What is the national flower of India?",
    answer: "Lotus.",
  },
  {
    id: 17,
    question: "What is the largest species of shark?",
    answer: "The whale shark.",
  },
  {
    id: 18,
    question: "Which country is home to the kangaroo?",
    answer: "Australia.",
  },
  {
    id: 19,
    question: "What is the largest bird in the world?",
    answer: "The ostrich.",
  },
  {
    id: 20,
    question: "What is the speed of light?",
    answer: "Approximately 299,792 kilometers per second.",
  },
];

export const feedData = [
  {
    id: "1",
    profile_img: mutual1,
    name: "Json Roy",
    snappy_username: "json1343",
    snapped_at: "15m",
    snapp: {
      message: "This is my First Snapp which I have snapped in this web site",
      image: snappImage,
    },
  },
  {
    id: "2",
    profile_img: mutual1,
    name: "Michelle Janny",
    snappy_username: "janny111",
    snapped_at: "Aug 21",
    snapp: {
      message:
        "ChatGPT is an advanced language model developed by OpenAI. Powered by the GPT-3.5 architecture, it is designed to generate human-like text and engage in interactive conversations with users. With a vast knowledge base and the ability to understand and respond to a wide range of topics, ChatGPT serves as a versatile tool for information retrieval, creative writing, and general conversation. It leverages its training on a diverse dataset to provide accurate and contextually appropriate responses to user queries. However, it is important to note that while ChatGPT is capable of producing coherent and fluent text, it may occasionally generate incorrect or nonsensical answers. Users should exercise critical thinking and verify information from reliable sources. OpenAI continues to refine and improve ChatGPT to enhance its capabilities and address any limitations or biases it may have",
      image: snappImage,
    },
  },
  {
    id: "3",
    profile_img: mutual1,
    name: "Smithy bou",
    snappy_username: "smithhh111",
    snapped_at: "21h",
    snapp: {
      message: "Hello Snappyess",
      image: snappImage,
    },
  },
  {
    id: "4",
    profile_img: mutual1,
    name: "Smithy bou",
    snappy_username: "smithhh111",
    snapped_at: "21h",
    snapp: {
      message:
        "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quia alias facilis, neque velit necessitatibus commodi222222!",
      image: snappImage,
    },
  },
  {
    id: "5",
    profile_img: mutual1,
    name: "Smithy bou",
    snappy_username: "smithhh111",
    snapped_at: "21h",
    snapp: {
      message:
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusamus maxime voluptates alias similique reprehenderit a suscipit adipisci nemo, debitis ullam incidunt tempora, aliquid animi natus illo neque accusantium. Repudiandae unde aperiam minus fugit deserunt tempore amet culpa, quae labore. Corporis?",
      image: snappImage,
    },
  },
  {
    id: "6",
    profile_img: mutual1,
    name: "Smithy bou",
    snappy_username: "smithhh111",
    snapped_at: "21h",
    snapp: {
      message:
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusamus maxime voluptates alias similique reprehenderit a suscipit adipisci nemo, debitis ullam incidunt tempora, aliquid animi natus illo neque accusantium. Repudiandae unde aperiam minus fugit deserunt tempore amet culpa, quae labore. Corporis?",
      image: snappImage,
    },
  },
];

export const singleFeedData = {
  id: "1",
  profile_img: mutual1,
  name: "Json Roy",
  snappy_username: "json1343",
  snapped_at: "12:53Pm Aug 8,2023",
  snapp: {
    message: "This is my First Snapp which I have snapped in this web site",
    image: snappImage,
  },
  likes: 39,
  bookmarks: 10,
  comments_count: 3,
  comments: [
    {
      id: 1,
      user_profile_pic: mutual1,
      user_name: "Alex",
      snapp_user_name: "aalex232e",
      commented_at: "23h",
      msg: "It is great",
      replied: [
        {
          id: 1,
          user_profile_pic: mutual2,
          user_name: "Kavya",
          snapp_user_name: "kavya123",
          commented_at: "27h",
          msg: "Where is the location Bro?",
        },
        {
          id: 2,
          user_profile_pic: mutual1,
          user_name: "Alex",
          snapp_user_name: "alex213",
          commented_at: "27h",
          msg: "Chennai",
        },
        {
          id: 3,
          user_profile_pic: mutual3,
          user_name: "Sam",
          snapp_user_name: "sam122",
          commented_at: "27h",
          msg: "Great It is awsome place I have vistied once",
        },
        {
          id: 4,
          user_profile_pic: mutual1,
          user_name: "Alex",
          snapp_user_name: "alex213",
          commented_at: "27h",
          msg: "yesssss.Its a greatt Place",
        },
      ],
    },
    {
      id: 2,
      user_profile_pic: mutual4,
      user_name: "Eoin",
      snapp_user_name: "eoin211",
      commented_at: "15m",
      msg: "Oh! It is wonderful",
    },
    {
      id: 3,
      user_profile_pic: mutual1,
      user_name: "Cary",
      snapp_user_name: "carry11323",
      commented_at: "23 June",
      msg: "New Life Starts is great",
      replied: [
        {
          id: 3,
          user_profile_pic: mutual3,
          user_name: "Sam",
          snapp_user_name: "sam122",
          commented_at: "27h",
          msg: "Great It is awsome place I have vistied once",
        },
        {
          id: 4,
          user_profile_pic: mutual1,
          user_name: "Alex",
          snapp_user_name: "alex213",
          commented_at: "27h",
          msg: "yesssss.Its a greatt Place",
        },
      ],
    },
    {
      id: 4,
      user_profile_pic: mutual4,
      user_name: "Ricky Rogers",
      snapp_user_name: "ricky754",
      commented_at: "May 01",
      msg: "I hope these wishes help you to express your love and appreciation for the special person in your life",
    },
  ],
};

// export const MockConnectorsList = [
//   {
//     id: 1,
//     name: "Jack",
//     profile_img: mutual1,
//     snappy_username: "jack111",
//     bio: "Lorem ipsum dolor sit amet, consectetur adipisicing.",
//     connected: true,
//   },
//   {
//     id: 2,
//     name: "Aaron",
//     profile_img: mutual2,
//     snappy_username: "aaron63211",
//     bio: "Lorem ipsu!",
//     connected: false,
//   },
//   {
//     id: 3,
//     name: "Antony",
//     profile_img: mutual3,
//     snappy_username: "antony76677",
//     bio: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Laborum voluptatum voluptates, culpa molestiae quam fugit laboriosam, non saepe veniam consequuntur vitae sapiente dicta.",
//     connected: true,
//   },
//   {
//     id: 4,
//     name: "Jenifer",
//     profile_img: mutual4,
//     snappy_username: "jenefier1213",
//     bio: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Neque autem temporibus necessitatibus dolor rem exercitationem, quos architecto aliquid laboriosam sed iste excepturi corrupti, quas ex ullam nulla error dolorum labore hic doloremque delectus, iure ipsum eius! Provident nisi nobis recusandae, sit optio deleniti voluptatem, esse sequi incidunt dolor corrupti cupiditate.",
//     connected: false,
//   },
//   {
//     id: 5,
//     name: "Antony",
//     profile_img: mutual3,
//     snappy_username: "antony76677",
//     bio: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur enim rerum molestiae.",
//     connected: true,
//   },
//   {
//     id: 6,
//     name: "Jenifer",
//     profile_img: mutual4,
//     snappy_username: "jenefier1213",
//     bio: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Rerum illo pariatur atque sit quaerat. Blanditiis at doloribus quisquam obcaecati?",
//     connected: false,
//   },
//   {
//     id: 7,
//     name: "Antony",
//     profile_img: mutual3,
//     snappy_username: "antony76677",
//     bio: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Neque autem temporibus necessitatibus dolor rem exercitationem, quos architecto aliquid laboriosam sed iste excepturi corrupti, quas ex ullam nulla error dolorum labore hic doloremque delectus, iure ipsum eius! Provident nisi nobis recusandae, sit optio deleniti voluptatem, esse sequi incidunt dolor corrupti cupiditate.",
//     connected: true,
//   },
//   {
//     id: 8,
//     name: "Jenifer",
//     profile_img: mutual4,
//     snappy_username: "jenefier1213",
//     bio: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Reprehenderit eos voluptates, odit veritatis mollitia debitis! Voluptates, tenetur, id vero, eius nesciunt reprehenderit eum ullam amet nobis quas sunt eveniet exercitationem nulla doloribus dolor officia tempore.",
//     connected: false,
//   },
// ];

export const mockReadOnlyEditor = [
  {
    type: "text",
    level: 7,
    children: [
      {
        text: "sadasdasdasd ",
      },
      {
        type: "hashtag",
        character: "sddasasd",
        children: [
          {
            text: "",
          },
        ],
      },
      {
        text: " ",
      },
      {
        type: "mention",
        character: "Sabine Wren",
        children: [
          {
            text: "",
          },
        ],
      },
      {
        text: " ",
      },
      {
        text: "sadasd ",
        bold: true,
      },
      {
        text: "asdasdsa ",
        italic: true,
      },
      {
        italic: true,
        text: "asdasd  ",
        underline: true,
      },
      {
        type: "emoji",
        character: "😅",
        children: [
          {
            text: "",
          },
        ],
      },
      {
        text: " ",
        italic: true,
        underline: true,
      },
      {
        type: "link",
        character: "asdas",
        url: "http://127.0.0.1:5173/",
        children: [
          {
            text: "",
          },
        ],
      },
      {
        text: "",
      },
    ],
  },
];

export const EditorMockD = [
  {
    type: "text",
    level: 7,
    children: [
      {
        text: "Hello all ",
      },
      {
        type: "emoji",
        character: "🙂",
        children: [
          {
            text: "",
          },
        ],
      },
      {
        text: ". How",
      },
      {
        text: " all are Doing",
        italic: true,
      },
      {
        text: "? ",
      },
      {
        text: "Today ",
        bold: true,
      },
      {
        text: "is the",
      },
      {
        text: " ",
        underline: true,
      },
      {
        text: "best day in my life",
        bold: true,
        underline: true,
      },
      {
        text: " ",
        underline: true,
      },
      {
        type: "emoji",
        character: "💯",
        children: [
          {
            text: "",
          },
        ],
      },
      {
        text: ". Because I am going to create my own Data Model.",
      },
      {
        type: "link",
        character: "My custom link I am providing",
        url: "http://127.0.0.1:5173/",
        children: [
          {
            text: "",
          },
        ],
      },
      {
        text: ".",
      },
    ],
  },
  {
    type: "text",
    level: 7,
    children: [
      {
        text: "And I am going to tell you ",
      },
      {
        type: "emoji",
        character: "🙂",
        children: [
          {
            text: "",
          },
        ],
      },
      {
        text: "some Tips",
        bold: true,
        italic: true,
      },
      {
        text: " . ",
      },
      {
        type: "link",
        character: "adqwed",
        url: "http://127.0.0.1:5173/",
        children: [
          {
            text: "",
          },
        ],
      },
      {
        text: "How you can be succeed in the life. And How you can ",
      },
      {
        text: "accept the happening",
        underline: true,
      },
      {
        text: ".",
      },
    ],
  },
  {
    type: "text",
    level: 7,
    children: [
      {
        text: "Then How can ",
      },
      {
        type: "emoji",
        character: "😘",
        children: [
          {
            text: "",
          },
        ],
      },
      {
        text: " you move your life toward the goal what ypu reallty needs tp accept. This is what you need to focus alway because we all need to be success in life.",
      },
    ],
  },
];

export const MockConnectorsList = [
  {
    personal_address: {
      state: "TN",
      country: "IND",
    },
    _id: "6558b3cbcf3abe872e55912c",
    first_name: "Celocious",
    last_name: "Altrin",
    user_name: "celo all15",
    email: "celociousalltrinmf@gmail.com",
    dob: "1999-12-14T18:30:00.000Z",
    phone_number: "918939401189",
    password: null,
    user_image: {
      public_id: "Snappy/user/ishgi8yxcpg4yxjb2rvp",
      secure_url:
        "https://res.cloudinary.com/dcbw3cocz/image/upload/v1700312011/Snappy/user/ishgi8yxcpg4yxjb2rvp.png",
    },
    about: [
      {
        type: "text",
        level: 7,
        children: [
          {
            text: "Working on My Dreams ",
          },
          {
            type: "emoji",
            character: "💯",
            children: [
              {
                text: "",
              },
            ],
          },
          {
            text: " ",
          },
          {
            type: "hashtag",
            character: "snappy",
            children: [
              {
                text: "",
              },
            ],
          },
          {
            text: " ",
          },
        ],
      },
    ],
    interest: [2, 5, 3, 12, 8],
    is_external_authenticated_user: true,
    __v: 0,
  },
  {
    personal_address: {
      state: "NY",
      country: "USA",
    },
    _id: "6558cbaa5a256f8389a4bc8b",
    first_name: "Maxwell",
    last_name: "M",
    user_name: "max1",
    email: "maxwell@gmail.com",
    dob: "1996-11-19T18:30:00.000Z",
    phone_number: "134567890",
    password: "$2a$10$hYpbenZBIMxIH9QfvcdBZ.MSNYiaB7SCBMzPrmGXqkS6vpM6j44LK",
    user_image: {
      public_id: "Snappy/user/ry99ruiy1sly3chzia2f",
      secure_url:
        "https://res.cloudinary.com/dcbw3cocz/image/upload/v1700318122/Snappy/user/ry99ruiy1sly3chzia2f.jpg",
    },
    about: [
      {
        type: "text",
        level: 7,
        children: [
          {
            text: "Trust the Process ",
          },
          {
            type: "emoji",
            character: "💯",
            children: [
              {
                text: "",
              },
            ],
          },
          {
            text: " ",
          },
          {
            type: "hashtag",
            character: "trust",
            children: [
              {
                text: "",
              },
            ],
          },
          {
            text: " ",
          },
        ],
      },
    ],
    interest: [19, 14, 13, 15, 20],
    is_external_authenticated_user: false,
    __v: 0,
  },
  {
    personal_address: {
      state: "GBN",
      country: "GBR",
    },
    _id: "6558d4639b091e4cf807b955",
    first_name: "maddy",
    last_name: "m",
    user_name: "mad maddy10",
    email: "maddy@gmail.com",
    dob: "1995-09-19T18:30:00.000Z",
    phone_number: "4423456",
    password: "$2a$10$vwUiHhCW22Q0EHyYe0Rk3ecrMwLeJCltamEqjJ.huqV7mlzDYFUWe",
    user_image: {
      public_id: "Snappy/user/yk0l0lsjba1podkwfeuq",
      secure_url:
        "https://res.cloudinary.com/dcbw3cocz/image/upload/v1700320354/Snappy/user/yk0l0lsjba1podkwfeuq.jpg",
    },
    about: [
      {
        type: "text",
        level: 7,
        children: [
          {
            text: "\"🌟 Explorer of life's adventures | ☕ Coffee enthusiast | 📚 Professional daydreamer | 🎶 Music addict | ✨ Turning ordinary into extraordinary | 280 characters can't capture my awesomeness!\"",
          },
        ],
      },
    ],
    interest: [6, 7, 8, 9, 13],
    is_external_authenticated_user: false,
    __v: 0,
  },
];

export const MockProfilePopoverData = {
  id: 1,
  name: "Jenifer",
  profile_img: mutual4,
  snappy_username: "jenefier1213",
  fans: 84,
  alliances: 11,
  bio: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Neque autem temporibus necessitatibus dolor rem exercitationem, quos architecto aliquid laboriosam sed iste excepturi corrupti, quas ex ullam nulla error dolorum labore hic doloremque delectus, iure ipsum eius! Provident nisi nobis recusandae, sit optio deleniti voluptatem, esse sequi incidunt dolor corrupti cupiditate.",
  connected: false,
};

export const mockNotifications = [
  {
    id: 1,
    name: "jack",
    snappy_user_name: "jack1322",
    profile_img: mutual1,
    type: 1,
    feed_id: "123",
    viewed: false,
    created_at: "2h",
  },
  {
    id: 2,
    name: "John",
    snappy_user_name: "john322",
    profile_img: mutual2,
    type: 2,
    feed_id: "135",
    viewed: true,
    created_at: "28 Juy",
  },
  {
    id: 3,
    name: "randy",
    snappy_user_name: "ran1233",
    profile_img: mutual3,
    type: 3,
    feed_id: "623",
    viewed: false,
    created_at: "4h",
  },
  {
    id: 4,
    name: "alexa",
    snappy_user_name: "alexa1322",
    profile_img: mutual4,
    type: 4,
    feed_id: null,
    viewed: false,
    created_at: "55m",
  },
  {
    id: 5,
    name: "Sam",
    snappy_user_name: "sam111",
    profile_img: mutual2,
    type: 5,
    feed_id: null,
    viewed: true,
    created_at: "2h",
  },
  {
    id: 6,
    name: "Jhansy",
    snappy_user_name: "jhansy543",
    profile_img: mutual1,
    type: 4,
    feed_id: null,
    viewed: false,
    created_at: "9h",
  },
  {
    id: 7,
    name: "jhon",
    snappy_user_name: "john121",
    profile_img: mutual4,
    type: 5,
    feed_id: "1993",
    viewed: false,
    created_at: "9 Aug",
  },
  {
    id: 8,
    name: "Mark",
    snappy_user_name: "mark431",
    profile_img: mutual2,
    type: 1,
    feed_id: "783",
    viewed: false,
    created_at: "just mow",
  },
];

export const mockProfileInfo = {
  id: 1,
  name: "Jack",
  snapp_user_name: "jack12432",
  profile_img: mutual4,
  banner_img: mutual1,
  bio: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Labore, sunt?",
  fans: 84,
  alliances: 11,
  created_at: "24 july 2023",
  snapp_count: 39,
};

export const mockSnappInfo = [
  {
    id: "1",
    profile_img: mutual1,
    name: "Json Roy",
    snappy_username: "json1343",
    snapped_at: "15m",
    snapp: {
      message: "This is my First Snapp which I have snapped in this web site",
      image: snappImage,
    },
  },
  {
    id: "2",
    profile_img: mutual1,
    name: "Json Roy",
    snappy_username: "json1343",
    snapped_at: "15m",
    snapp: {
      message: "This is my First Snapp which I have snapped in this web site",
      image: snappImage,
      pinned_snapp: true,
    },
  },
  {
    id: "3",
    profile_img: mutual1,
    name: "Json Roy",
    snappy_username: "json1343",
    snapped_at: "15m",
    snapp: {
      message:
        "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Blanditiis, sequi!",
      image: snappImage,
      pinned_snapp: false,
    },
  },
  {
    id: "4",
    profile_img: mutual1,
    name: "Json Roy",
    snappy_username: "json1343",
    snapped_at: "15m",
    snapp: {
      message: "This is my First Snapp which I have snapped in this web site",
      image: snappImage,
      pinned_snapp: false,
    },
  },
  {
    id: "5",
    profile_img: mutual1,
    name: "Json Roy",
    snappy_username: "json1343",
    snapped_at: "15m",
    snapp: {
      message: "Lorem ipsum dolor sit amet consectetur adipisicing.",
      image: snappImage,
      pinned_snapp: false,
    },
  },
];

export const mockEditProfileInfo = {
  id: 1,
  profile_img: mutual4,
  banner_img: mutual1,
  bio: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Labore, sunt?",
  dob: "15 Dec 1999",
};

export const mockMessageInfo = [
  {
    id: 1,
    users: {
      profile_img: mutual1,
      user_name: "Jack",
      snappy_user_name: "jack125",
      connected: true,
      last_seen: "today at 12:31 pm",
    },
    convesation: [
      {
        from: "john",
        msg: "Hi Bro, How are you?",
        is_read: true,
        created_at: "23 july 10:47 am",
      },
      {
        from: "Jack",
        msg: "Great Bro",
        is_read: true,
        created_at: "23 july 10:49 am",
      },
      {
        from: "john",
        msg: "How is life going?",
        is_read: true,
        created_at: "23 july 10:57 am",
      },
      {
        from: "jack",
        msg: "Nice",
        is_read: true,
        created_at: "23 july 11:47 am",
      },
      {
        from: "jack",
        msg: "Hi about you bro?",
        is_read: true,
        created_at: "23 july 11:57 am",
      },
      {
        from: "john",
        msg: "Fine bro",
        is_read: true,
        created_at: "23 july 12:47 am",
      },
      {
        from: "jack",
        msg: "Now where are you bro",
        is_read: false,
        created_at: "23 july 10:47 am",
      },
    ],
    is_clear: false,
  },
  {
    id: 2,
    users: {
      profile_img: mutual4,
      user_name: "Milly",
      snappy_user_name: "milly125",
      connected: false,
      last_seen: "today at 12:31 pm",
    },
    convesation: [
      {
        from: "jack",
        msg: "Hi Sis, How are you?",
        is_read: true,
        created_at: "23 july 10:47 am",
      },
      {
        from: "Milly",
        msg: "Great Bro",
        is_read: true,
        created_at: "23 july 10:49 am",
      },
    ],
    is_clear: false,
  },
  {
    id: 3,
    users: {
      profile_img: mutual2,
      user_name: "Milly",
      snappy_user_name: "milly125",
      connected: true,
      last_seen: "today at 12:31 pm",
    },
    convesation: [
      {
        from: "jack",
        msg: "Hi Sis, How are you?",
        is_read: true,
        created_at: "23 july 10:47 am",
      },
      {
        from: "Milly",
        msg: "Great Bro",
        is_read: true,
        created_at: "23 july 10:49 am",
      },
      {
        from: "Milly",
        msg: "Hello",
        is_read: false,
        created_at: "23 july 10:49 am",
      },
      {
        from: "Milly",
        msg: "Are you there",
        is_read: false,
        created_at: "23 july 10:49 am",
      },
    ],
    is_clear: false,
  },
  {
    id: 4,
    users: {
      profile_img: mutual1,
      user_name: "Milly",
      snappy_user_name: "milly125",
      connected: true,
      last_seen: "today at 12:31 pm",
    },
    convesation: [
      {
        from: "jack",
        msg: "Hi Sis, How are you?",
        is_read: true,
        created_at: "23 july 10:47 am",
      },
      {
        from: "Milly",
        msg: "Great Bro, Today is the nice day in which we are planning to go outside",
        is_read: true,
        created_at: "23 july 10:49 am",
      },
    ],
    is_clear: false,
  },
  {
    id: 5,
    users: {
      profile_img: mutual3,
      user_name: "Ezhumalai",
      snappy_user_name: "ezhumalai323",
      connected: false,
      last_seen: "today at 12:31 pm",
    },
    convesation: [
      {
        from: "jack",
        msg: "Hi Bro, How are you?",
        is_read: true,
        created_at: "23 july 10:47 am",
      },
      {
        from: "Ezhumalai",
        msg: "Great Bro",
        is_read: true,
        created_at: "23 july 10:49 am",
      },
      {
        from: "jack",
        msg: "How is life going?",
        is_read: false,
        created_at: "23 july 10:57 am",
      },
      {
        from: "jack",
        msg: "Bro?",
        is_read: false,
        created_at: "23 july 10:57 am",
      },
      {
        from: "jack",
        msg: "Reply Bro?",
        is_read: false,
        created_at: "23 july 10:57 am",
      },
    ],
    is_clear: false,
  },
  {
    id: 6,
    users: {
      profile_img: mutual1,
      user_name: "Arumugam",
      snappy_user_name: "ezhumalai323",
      connected: false,
      last_seen: "today at 12:31 pm",
    },
    convesation: [
      {
        from: "jack",
        msg: "Hi Bro, How are you?",
        is_read: true,
        created_at: "23 july 10:47 am",
      },
      {
        from: "Arumugam",
        msg: "Great Bro",
        is_read: true,
        created_at: "23 july 10:49 am",
      },
      {
        from: "jack",
        msg: "How is life going?",
        is_read: true,
        created_at: "23 july 10:57 am",
      },
      {
        from: "jack",
        msg: "Bro?",
        is_read: true,
        created_at: "23 july 10:57 am",
      },
      {
        from: "jack",
        msg: "Bro?",
        is_read: true,
        created_at: "23 july 10:57 am",
      },
    ],
    is_clear: false,
  },
];

export const mockChatInfo = {
  user_name: "jack",
  snappy_user_name: "jack12422",
  profile_image: mutual2,
  connected: false,
  last_seen: "today at 12:31 pm",
  conversation: [
    { from: "jack12422", msg: "Hi Bro ?", is_read: "true" },
    { from: "john878", msg: "Fine ?", is_read: "true" },
    {
      from: "jack12422",
      msg: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Assumenda, nesciunt.",
      is_read: "true",
    },
    {
      from: "john878",
      msg: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Esse odio sunt fugiat placeat deserunt. Temporibus non quasi repellendus.",
      is_read: "true",
    },
    { from: "jack12422", msg: "Bro this is WHich Language", is_read: "true" },
    { from: "jack12422", msg: "Bro reply Bro?", is_read: "true" },
    { from: "john878", msg: "Yeah bro", is_read: "true" },
    { from: "john878", msg: "Whats the issue bro", is_read: "true" },
    { from: "john878", msg: "I am there for you bro", is_read: "true" },
    {
      from: "jack12422",
      msg: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Assumenda, nesciunt.",
      is_read: "true",
    },
    {
      from: "john878",
      msg: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Esse odio sunt fugiat placeat deserunt. Temporibus non quasi repellendus.",
      is_read: "true",
    },
    { from: "jack12422", msg: "Bro this is WHich Language", is_read: "true" },
    { from: "jack12422", msg: "Bro reply Bro?", is_read: "true" },
    { from: "john878", msg: "Yeah bro", is_read: "true" },
    { from: "john878", msg: "Whats the issue bro", is_read: "true" },
    { from: "john878", msg: "I am there for you bro", is_read: "true" },
  ],
};

export const mockMentionUsers = [
  "Aayla Secura",
  "Adi Gallia",
  "Admiral Dodd Rancit",
  "Admiral Firmus Piett",
  "Admiral Gial Ackbar",
  "Admiral Ozzel",
  "Admiral Raddus",
  "Admiral Terrinald Screed",
  "Admiral Trench",
  "Admiral U.O. Statura",
  "Agen Kolar",
  "Agent Kallus",
  "Aiolin and Morit Astarte",
  "Aks Moe",
  "Almec",
  "Alton Kastle",
  "Amee",
  "AP-5",
  "Armitage Hux",
  "Artoo",
  "Arvel Crynyd",
  "Asajj Ventress",
  "Aurra Sing",
  "AZI-3",
  "Bala-Tik",
  "Barada",
  "Bargwill Tomder",
  "Baron Papanoida",
  "Barriss Offee",
  "Baze Malbus",
  "Bazine Netal",
  "BB-8",
  "BB-9E",
  "Ben Quadinaros",
  "Berch Teller",
  "Beru Lars",
  "Bib Fortuna",
  "Biggs Darklighter",
  "Black Krrsantan",
  "Bo-Katan Kryze",
  "Boba Fett",
  "Bobbajo",
  "Bodhi Rook",
  "Borvo the Hutt",
  "Boss Nass",
  "Bossk",
  "Breha Antilles-Organa",
  "Bren Derlin",
  "Brendol Hux",
  "BT-1",
  "C-3PO",
  "C1-10P",
  "Cad Bane",
  "Caluan Ematt",
  "Captain Gregor",
  "Captain Phasma",
  "Captain Quarsh Panaka",
  "Captain Rex",
  "Carlist Rieekan",
  "Casca Panzoro",
  "Cassian Andor",
  "Cassio Tagge",
  "Cham Syndulla",
  "Che Amanwe Papanoida",
  "Chewbacca",
  "Chi Eekway Papanoida",
  "Chief Chirpa",
  "Chirrut Îmwe",
  "Ciena Ree",
  "Cin Drallig",
  "Clegg Holdfast",
  "Cliegg Lars",
  "Coleman Kcaj",
  "Coleman Trebor",
  "Colonel Kaplan",
  "Commander Bly",
  "Commander Cody (CC-2224)",
  "Commander Fil (CC-3714)",
  "Commander Fox",
  "Commander Gree",
  "Commander Jet",
  "Commander Wolffe",
  "Conan Antonio Motti",
  "Conder Kyl",
  "Constable Zuvio",
  "Cordé",
  "Cpatain Typho",
  "Crix Madine",
  "Cut Lawquane",
  "Dak Ralter",
  "Dapp",
  "Darth Bane",
  "Darth Maul",
  "Darth Tyranus",
  "Daultay Dofine",
  "Del Meeko",
  "Delian Mors",
  "Dengar",
  "Depa Billaba",
  "Derek Klivian",
  "Dexter Jettster",
  "Dineé Ellberger",
  "DJ",
  "Doctor Aphra",
  "Doctor Evazan",
  "Dogma",
  "Dormé",
  "Dr. Cylo",
  "Droidbait",
  "Droopy McCool",
  "Dryden Vos",
  "Dud Bolt",
  "Ebe E. Endocott",
  "Echuu Shen-Jon",
  "Eeth Koth",
  "Eighth Brother",
  "Eirtaé",
  "Eli Vanto",
  "Ellé",
  "Ello Asty",
  "Embo",
  "Eneb Ray",
  "Enfys Nest",
  "EV-9D9",
  "Evaan Verlaine",
  "Even Piell",
  "Ezra Bridger",
  "Faro Argyus",
  "Feral",
  "Fifth Brother",
  "Finis Valorum",
  "Finn",
  "Fives",
  "FN-1824",
  "FN-2003",
  "Fodesinbeed Annodue",
  "Fulcrum",
  "FX-7",
  "GA-97",
  "Galen Erso",
  "Gallius Rax",
  'Garazeb "Zeb" Orrelios',
  "Gardulla the Hutt",
  "Garrick Versio",
  "Garven Dreis",
  "Gavyn Sykes",
  "Gideon Hask",
  "Gizor Dellso",
  "Gonk droid",
  "Grand Inquisitor",
  "Greeata Jendowanian",
  "Greedo",
  "Greer Sonnel",
  "Grievous",
  "Grummgar",
  "Gungi",
  "Hammerhead",
  "Han Solo",
  "Harter Kalonia",
  "Has Obbit",
  "Hera Syndulla",
  "Hevy",
  "Hondo Ohnaka",
  "Huyang",
  "Iden Versio",
  "IG-88",
  "Ima-Gun Di",
  "Inquisitors",
  "Inspector Thanoth",
  "Jabba",
  "Jacen Syndulla",
  "Jan Dodonna",
  "Jango Fett",
  "Janus Greejatus",
  "Jar Jar Binks",
  "Jas Emari",
  "Jaxxon",
  "Jek Tono Porkins",
  "Jeremoch Colton",
  "Jira",
  "Jobal Naberrie",
  "Jocasta Nu",
  "Joclad Danva",
  "Joh Yowza",
  "Jom Barell",
  "Joph Seastriker",
  "Jova Tarkin",
  "Jubnuk",
  "Jyn Erso",
  "K-2SO",
  "Kanan Jarrus",
  "Karbin",
  "Karina the Great",
  "Kes Dameron",
  "Ketsu Onyo",
  "Ki-Adi-Mundi",
  "King Katuunko",
  "Kit Fisto",
  "Kitster Banai",
  "Klaatu",
  "Klik-Klak",
  "Korr Sella",
  "Kylo Ren",
  "L3-37",
  "Lama Su",
  "Lando Calrissian",
  "Lanever Villecham",
  "Leia Organa",
  "Letta Turmond",
  "Lieutenant Kaydel Ko Connix",
  "Lieutenant Thire",
  "Lobot",
  "Logray",
  "Lok Durd",
  "Longo Two-Guns",
  "Lor San Tekka",
  "Lorth Needa",
  "Lott Dod",
  "Luke Skywalker",
  "Lumat",
  "Luminara Unduli",
  "Lux Bonteri",
  "Lyn Me",
  "Lyra Erso",
  "Mace Windu",
  "Malakili",
  "Mama the Hutt",
  "Mars Guo",
  "Mas Amedda",
  "Mawhonic",
  "Max Rebo",
  "Maximilian Veers",
  "Maz Kanata",
  "ME-8D9",
  "Meena Tills",
  "Mercurial Swift",
  "Mina Bonteri",
  "Miraj Scintel",
  "Mister Bones",
  "Mod Terrik",
  "Moden Canady",
  "Mon Mothma",
  "Moradmin Bast",
  "Moralo Eval",
  "Morley",
  "Mother Talzin",
  "Nahdar Vebb",
  "Nahdonnis Praji",
  "Nien Nunb",
  "Niima the Hutt",
  "Nines",
  "Norra Wexley",
  "Nute Gunray",
  "Nuvo Vindi",
  "Obi-Wan Kenobi",
  "Odd Ball",
  "Ody Mandrell",
  "Omi",
  "Onaconda Farr",
  "Oola",
  "OOM-9",
  "Oppo Rancisis",
  "Orn Free Taa",
  "Oro Dassyne",
  "Orrimarko",
  "Osi Sobeck",
  "Owen Lars",
  "Pablo-Jill",
  "Padmé Amidala",
  "Pagetti Rook",
  "Paige Tico",
  "Paploo",
  "Petty Officer Thanisson",
  "Pharl McQuarrie",
  "Plo Koon",
  "Po Nudo",
  "Poe Dameron",
  "Poggle the Lesser",
  "Pong Krell",
  "Pooja Naberrie",
  "PZ-4CO",
  "Quarrie",
  "Quay Tolsite",
  "Queen Apailana",
  "Queen Jamillia",
  "Queen Neeyutnee",
  "Qui-Gon Jinn",
  "Quiggold",
  "Quinlan Vos",
  "R2-D2",
  "R2-KT",
  "R3-S6",
  "R4-P17",
  "R5-D4",
  "RA-7",
  "Rabé",
  "Rako Hardeen",
  "Ransolm Casterfo",
  "Rappertunie",
  "Ratts Tyerell",
  "Raymus Antilles",
  "Ree-Yees",
  "Reeve Panzoro",
  "Rey",
  "Ric Olié",
  "Riff Tamson",
  "Riley",
  "Rinnriyin Di",
  "Rio Durant",
  "Rogue Squadron",
  "Romba",
  "Roos Tarpals",
  "Rose Tico",
  "Rotta the Hutt",
  "Rukh",
  "Rune Haako",
  "Rush Clovis",
  "Ruwee Naberrie",
  "Ryoo Naberrie",
  "Sabé",
  "Sabine Wren",
  "Saché",
  "Saelt-Marae",
  "Saesee Tiin",
  "Salacious B. Crumb",
  "San Hill",
  "Sana Starros",
  "Sarco Plank",
  "Sarkli",
  "Satine Kryze",
  "Savage Opress",
  "Sebulba",
  "Senator Organa",
  "Sergeant Kreel",
  "Seventh Sister",
  "Shaak Ti",
  "Shara Bey",
  "Shmi Skywalker",
  "Shu Mai",
  "Sidon Ithano",
  "Sifo-Dyas",
  "Sim Aloo",
  "Siniir Rath Velus",
  "Sio Bibble",
  "Sixth Brother",
  "Slowen Lo",
  "Sly Moore",
  "Snaggletooth",
  "Snap Wexley",
  "Snoke",
  "Sola Naberrie",
  "Sora Bulq",
  "Strono Tuggs",
  "Sy Snootles",
  "Tallissan Lintra",
  "Tarfful",
  "Tasu Leech",
  "Taun We",
  "TC-14",
  "Tee Watt Kaa",
  "Teebo",
  "Teedo",
  "Teemto Pagalies",
  "Temiri Blagg",
  "Tessek",
  "Tey How",
  "Thane Kyrell",
  "The Bendu",
  "The Smuggler",
  "Thrawn",
  "Tiaan Jerjerrod",
  "Tion Medon",
  "Tobias Beckett",
  "Tulon Voidgazer",
  "Tup",
  "U9-C4",
  "Unkar Plutt",
  "Val Beckett",
  "Vanden Willard",
  "Vice Admiral Amilyn Holdo",
  "Vober Dand",
  "WAC-47",
  "Wag Too",
  "Wald",
  "Walrus Man",
  "Warok",
  "Wat Tambor",
  "Watto",
  "Wedge Antilles",
  "Wes Janson",
  "Wicket W. Warrick",
  "Wilhuff Tarkin",
  "Wollivan",
  "Wuher",
  "Wullf Yularen",
  "Xamuel Lennox",
  "Yaddle",
  "Yarael Poof",
  "Yoda",
  "Zam Wesell",
  "Zev Senesca",
  "Ziro the Hutt",
  "Zuckuss",
];
